name: RouteSG
main: net.routemc.sg.RouteSG
version: 2.0
depend: [RouteCore, RequiresAPI]
commands:
  rsg:
  spec:
  stats:
  bb:
  list:
    aliases: [l]
  vote:
    aliases: [v]
  gf:
  host:
  givehost:
  register:
  unregister:
  frkbreload:
  roster:
  team:
    aliases: [t]
  observer:
  kc:
  tc:
  fl:
  tl:
  kt: