name: HotsSG
main: net.hotsmc.sg.HSG
version: 2.0
softdepend: [HotsCore]
commands:
  hsg:
  spec:
  stats:
  sponsor:
  list:
    aliases: [l]
  vote:
    aliases: [v]
  gf:
  host:
  givehost:
  register:
  unregister:
  frkbreload:
  roster:
  team:
  observer:
  kc:
  tc:
  fl:
  tl:
  kt: